### ISSUE TITLE
Zip saving issue

### ISSUE THREAD

**Issue by Kaan88** [meefik/busybox#1]
No matter what path I choose the app is unable to save the archive. App has root permissions, and I've tried setting selinux to permissive also. 

System is android 6.0

**Comment by meefik** [comment]
You must allow the application access to the storage:
Settings -> Apps -> BusyBox -> Permissions -> Storage -> On

**Comment by Kaan88** [comment]
That did it, thanks. It never asked though?

**Comment by meefik** [comment]
This will be fixed in the next version.
