### ISSUE TITLE
Some links appear to be missing, & ssl_helper not installed.

### ISSUE THREAD

**Issue by DiagonalArg** [meefik/busybox#103]
I just installed 1.31.1 on an Android 7.1.2 ROM.  Log is as follows:

```
### BEGIN INSTALL
Remounting /system to rw ... done
Copying busybox to /system/xbin ... done
Changing permissions for busybox ... done
Copying ssl_helper to /system/xbin ... fail
Changing permissions for ssl_helper ... fail
Removing old applets ... done
Installing new applets ... done
Installing addon.d script ... done
Remounting /system to ro ... done
### END
```
Not sure of the implications of failure to install ssl_helper.

This install was over an old busybox, which allowed me to notice that yours did not over-write 17 of the old links, even though 6 of them appear to work fine:
```
chcon
restorecon
runcon

getenforce
setenforce

setarch
```

Three do not work but appear to  still be a [part of the busybox project](https://busybox.net/downloads/BusyBox.html):
```
catv
flash_lock
flash_unlock
```

And 8 others in addition no longer function.  I'm supposing they are no longer in the project (?):
```
flashcp

getsebool
setsebool

matchpathcon

nanddump
nandwrite

selinuxenabled
setfiles
```

**Comment by superbonaci** [comment]
Probably you are not root or busybox does not have root enabled. Are you on LineageOS with Magisk?

**Comment by DiagonalArg** [comment]
@superbonaci - let's see ... that was LineageOS on an old Nook.  Rooted.  No Magisk, just SuperSU.

**Comment by superbonaci** [comment]
Can you try today with newest LineageOS build and everything else too?

**Comment by DiagonalArg** [comment]
Sorry, @superbonaci - That old nook is no longer supported, and in any case it's in storage.

If you need to close this, then go ahead.

**Comment by superbonaci** [comment]
You close it since are the original poster.

**Comment by DiagonalArg** [comment]
Alright.  Thanks.
