### ISSUE TITLE
trim on f2fs

### ISSUE THREAD

**Issue by soredake** [meefik/busybox#12]
su
root@Z00A:/ # fstrim -v /data
fstrim: FITRIM: Not a typewriter
root@Z00A:/ #

**Comment by cloud9350** [comment]
This is not busybox error.

**Comment by sm4rk0** [comment]
This means that the filesystem mounted at /data is probably f2fs which already [does TRIM internally](https://plus.google.com/+ChetKener/posts/7No16fUQaFz). You can check the FS type with `mount` command.
