### ISSUE TITLE
Where did assets/arm/bin/busybox go? Now there is only lib/armeabi-v7a/libbusybox.so

### ISSUE THREAD

**Issue by rubenpgrady** [meefik/busybox#123]
Thank you very much for working on this project! :heart: 

I've been using your build of BusyBox since [1.31.1](https://github.com/meefik/busybox/releases/tag/1.31.1). I simply extracted the APK file and took the binary `assets/arm/bin/busybox` and copied it to my device. And this worked (and still works!) perfectly so, again, thank you very much for your work.

However, with [1.34.1](https://github.com/meefik/busybox/releases/tag/1.34.1), I cannot use your build anymore, because, there is no `busybox` binaries, anymore. I can only find `lib/armeabi-v7a/libbusybox.so`. What changed? Can I make this `.so` file executable?

I'd appreciate it if you can find the time to reply. Thanks!

**Comment by meefik** [comment]
The `libbusybox.so` file is an executable binary file. You can symlink or copy the file to `busybox`.

**Comment by rubenpgrady** [comment]
Thank you very much. :+1:
