### ISSUE TITLE
Traditional Chinese translation does not work

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [meefik/busybox#20]
Steps:
1. Download & install [BusyBox 1.25.1](https://github.com/meefik/busybox/releases/tag/1.25.1)
2. Settings > Language > 中国传统
3. Go back
4. Traditional Chinese translation is not display, instead is Simplified Chinese.

To fix it, the values-zh path should rename as values-zh-rCN and merge #19.

**Comment by meefik** [comment]
Fixed. If OK then close the issue.

**Comment by KrasnayaPloshchad** [comment]
OK, it’s good.
