### ISSUE TITLE
lsblk command not found

### ISSUE THREAD

**Issue by Anan5a** [meefik/busybox#33]
![img_20170203_121254](https://cloud.githubusercontent.com/assets/16373480/22581435/26cc2100-ea0a-11e6-8472-8c0ba3286a1d.JPG)
 ``` lsblk ```  command was not found.
## Please add this feature in future update :)

**Comment by hyiltiz** [comment]
That is hardly in the scope of busybox.

**Comment by Anan5a** [comment]
However i figured out a solution. :)

**Comment by hyiltiz** [comment]
It would help to list what workaround you found, so the next one as yourself would find that helpful.
