### ISSUE TITLE
Question : Differences between your busybox and stericson.busybox ?

### ISSUE THREAD

**Issue by sebma** [meefik/busybox#63]
Hi,

[f-droid.org](https://f-droid.org/packages/ru.meefik.busybox/) says that your application : 

> Install a recent and un-crippled version of BusyBox.

What do you (or f-droid) mean by "un-crippled version", can you please be more precise ?

**Comment by TheAlienDrew** [comment]
Most BusyBox apps that install the extra features are out of date and not being kept up to date with the newest features being programmed. Besides that, Meefik also programs extra features that makes apps such as Linux Deploy (another app made by the same guy) work, allowing a chroot environment of Linux (on rooted devices).

**Comment by endless-love** [comment]
How do I safely replace stericson.busybox with this one?

**Comment by cyfrost** [comment]
@endless-love

I used the stericson.busybox for so long before deciding it no good compared to Meefik's busybox.

I simply uninstalled Stericson's busybox using the Uninstall button in the app. Installed Meefik's one and it didn't cause any problems whatsoever.

Both of these installers install busybox binaries to /system/xbin. Let me know if it worked for you too.

**Comment by endless-love** [comment]
@cyfrost

I was scared because of the warning when trying to uninstall, but it just uninstalled successfully. Thank you.

I just install Meefik's BusyBox now and get some errors about ssl_helper, here is the log file with Debug and Trace enabled: https://pastebin.com/89BWMHGn

Is that normal?

**Comment by meefik** [comment]
File /data/user/0/ru.meefik.busybox/files/bin/ssl_helper not found..
What is your version of the BusyBox application (Menu -> About)? Latest version 1.28.4-37.

**Comment by endless-love** [comment]
I'm using 1.28.4-37 from F-Droid

**Comment by meefik** [comment]
Hm.. May be F-Droid maintainer not include ssl_helper in the build..

**Comment by sebma** [comment]
@endless-love @cyfrost @meefik Hi,

Why not move the `ssl_helper not found` discussion to a dedicated issue so that other people can find your discussion using the search button in the [Issues](https://github.com/meefik/busybox/issues) tab ?
