### ISSUE TITLE
Update fdroid repo

### ISSUE THREAD

**Issue by Oi69qEZ** [meefik/busybox#88]
Why the app in fdroid is still 1.30.1 ? And here in github and in playstore it's 1.31.1
Acording to the main site, 1.31.1 is stable

**Comment by AnaelMobilia** [comment]
@Oi69qEZ  F-droid team rebuild packages from source (automatically ;-)) and don't use released provide by the developper.

On the F-droid gitlab appears an error for this version : "disable: broken build, missing ssl_helper".

I suggest you to open an issue to F-Droid developpers to fix the build on their servers.

Regards,
Anael

**Comment by meefik** [comment]
I added the automation scripts for complete build:
```
./gradlew assets
./gradlew build
```

**Comment by licaon-kter** [comment]
This can be closed, ref: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6454/diffs

**Comment by Mannshoch** [comment]
Why does it still not work?

**Comment by licaon-kter** [comment]
You mean why this has not been updated? We didn't know a new version is out, and it's not on autoupdate iirc.

**Comment by licaon-kter** [comment]
@Mannshoch https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10763
